fix: load config using yaml.safe_load(), not yaml.load()
Attempt to address exception:

    Traceback (most recent call last):
      File "/edx/app/ecomworker/venvs/ecomworker/bin/celery", line 8, in <module>
        sys.exit(main())
      File "/edx/app/ecomworker/venvs/ecomworker/lib/python3.8/site-packages/celery/__main__.py", line 16, in main
        _main()
      File "/edx/app/ecomworker/venvs/ecomworker/lib/python3.8/site-packages/celery/bin/celery.py", line 322, in main
        cmd.execute_from_commandline(argv)
      File "/edx/app/ecomworker/venvs/ecomworker/lib/python3.8/site-packages/celery/bin/celery.py", line 499, in execute_from_commandline
        super(CeleryCommand, self).execute_from_commandline(argv)))
      File "/edx/app/ecomworker/venvs/ecomworker/lib/python3.8/site-packages/celery/bin/base.py", line 305, in execute_from_commandline
        return self.handle_argv(self.prog_name, argv[1:])
    [...]
      File "/edx/app/ecomworker/venvs/ecomworker/lib/python3.8/site-packages/celery/app/base.py", line 920, in _finalize_pending_conf
        conf = self._conf = self._load_config()
      File "/edx/app/ecomworker/venvs/ecomworker/lib/python3.8/site-packages/celery/app/base.py", line 930, in _load_config
        self.loader.config_from_object(self._config_source)
    [...]
      File "/edx/app/ecomworker/ecomworker/ecommerce_worker/configuration/production.py", line 18, in <module>
        config_from_yaml = yaml.load(f)
    TypeError: load() missing 1 required positional argument: 'Loader'

Docs: https://pyyaml.org/wiki/PyYAMLDocumentation#loading-yaml